name: Docker Image for Qwen 3 llm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_VEEM }}
          password: ${{ secrets.DOCKER_PASSWORD_VEEM }}
      
      - name: Set up Docker image tag
        run: echo "IMAGE_TAG=veem2030/qwen-3-llm:$(date +%s)" >> $GITHUB_ENV
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }} 
      
      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_TAG }}
